'use strict';

const express = require('express');
const axios = require('axios');
const { Pool } = require('pg');
const { chtToFhirSupplyDelivery } = require('../mapper');

const router = express.Router();

// PostgreSQL pool (populated by CHT-Sync)
const pool = new Pool({
  host:     process.env.PG_HOST     || 'postgres',
    port:     parseInt(process.env.PG_PORT || '5432'),
      database: process.env.PG_DB       || 'cht_sync',
        user:     process.env.PG_USER     || 'cht',
          password: process.env.PG_PASSWORD || 'cht-password'
          });

          const ILMIS_URL  = process.env.ILMIS_URL  || 'http://ilmis-stub:4500';
          const DHIS2_URL  = process.env.DHIS2_URL  || 'http://dhis2-stub:4501';
          const DHIS2_AUTH = {
            username: process.env.DHIS2_USER || 'admin',
              password: process.env.DHIS2_PASS || 'district'
              };

              /**
               * POST /stock-report
                * Body: CHT stock_report document (JSON)
                 * 1. Convert to FHIR SupplyDelivery
                  * 2. POST to iLMIS stub
                   * 3. Forward summary to DHIS2 Tracker stub
                    * 4. Persist summary to PostgreSQL for dashboard
                     */
                     router.post('/', async (req, res) => {
                       try {
                           const doc = req.body;

                               if (!doc || !doc._id) {
                                     return res.status(400).json({ error: 'Invalid CHT document — missing _id' });
                                         }

                                             // 1. Map to FHIR R4
                                                 const fhirResource = chtToFhirSupplyDelivery(doc);

                                                     // 2. Forward to iLMIS stub
                                                         let ilmisResponse = null;
                                                             try {
                                                                   const r = await axios.post(`${ILMIS_URL}/fhir/SupplyDelivery`, fhirResource, {
                                                                           headers: { 'Content-Type': 'application/fhir+json' },
                                                                                   timeout: 5000
                                                                                         });
                                                                                               ilmisResponse = { status: r.status, id: r.data?.id };
                                                                                                   } catch (ilmisErr) {
                                                                                                         ilmisResponse = { error: ilmisErr.message };
                                                                                                             }
                                                                                                             
                                                                                                                 // 3. Forward to DHIS2 stub (simplified Tracker event payload)
                                                                                                                     const dhis2Payload = {
                                                                                                                           events: [{
                                                                                                                                   program: 'CHP_STOCK_PROGRAM',
                                                                                                                                           orgUnit: doc.contact?.parent?._id || 'unknown',
                                                                                                                                                   eventDate: new Date(doc.reported_date).toISOString().split('T')[0],
                                                                                                                                                           status: 'COMPLETED',
                                                                                                                                                                   dataValues: Object.entries({
                                                                                                                                                                             amoxicillin: doc.fields?.amoxicillin_stock,
                                                                                                                                                                                       ors: doc.fields?.ors_stock,
                                                                                                                                                                                                 zinc: doc.fields?.zinc_stock,
                                                                                                                                                                                                           rdt: doc.fields?.rdt_stock,
                                                                                                                                                                                                                     fp_pills: doc.fields?.fp_pills_stock,
                                                                                                                                                                                                                               fp_injectables: doc.fields?.fp_injectables_stock
                                                                                                                                                                                                                                       }).map(([key, value]) => ({ dataElement: `CHP_${key.toUpperCase()}`, value: value ?? 0 }))
                                                                                                                                                                                                                                             }]
                                                                                                                                                                                                                                               };
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                   let dhis2Response = null;
                                                                                                                                                                                                                                                       try {
                                                                                                                                                                                                                                                             const r = await axios.post(`${DHIS2_URL}/api/events`, dhis2Payload, {
                                                                                                                                                                                                                                                                     auth: DHIS2_AUTH,
                                                                                                                                                                                                                                                                             headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                     timeout: 5000
                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                 dhis2Response = { status: r.status };
                                                                                                                                                                                                                                                                                                     } catch (dhis2Err) {
                                                                                                                                                                                                                                                                                                           dhis2Response = { error: dhis2Err.message };
                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                   // 4. Persist to PostgreSQL
                                                                                                                                                                                                                                                                                                                       const stockoutFlags = fhirResource.extension?.length > 0;
                                                                                                                                                                                                                                                                                                                           try {
                                                                                                                                                                                                                                                                                                                                 await pool.query(
                                                                                                                                                                                                                                                                                                                                         `INSERT INTO stock_reports (doc_id, chp_id, chp_name, chu_id, reported_date, fields, has_stockout, fhir_resource)
                                                                                                                                                                                                                                                                                                                                                  VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
                                                                                                                                                                                                                                                                                                                                                           ON CONFLICT (doc_id) DO UPDATE SET fields=$6, has_stockout=$7, fhir_resource=$8`,
                                                                                                                                                                                                                                                                                                                                                                   [
                                                                                                                                                                                                                                                                                                                                                                               doc._id,
                                                                                                                                                                                                                                                                                                                                                                                         doc.contact?._id,
                                                                                                                                                                                                                                                                                                                                                                                                   doc.contact?.name,
                                                                                                                                                                                                                                                                                                                                                                                                             doc.contact?.parent?._id,
                                                                                                                                                                                                                                                                                                                                                                                                                       new Date(doc.reported_date),
                                                                                                                                                                                                                                                                                                                                                                                                                                 JSON.stringify(doc.fields),
                                                                                                                                                                                                                                                                                                                                                                                                                                           stockoutFlags,
                                                                                                                                                                                                                                                                                                                                                                                                                                                     JSON.stringify(fhirResource)
                                                                                                                                                                                                                                                                                                                                                                                                                                                             ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } catch (pgErr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Non-fatal — log and continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 console.error('PostgreSQL insert error:', pgErr.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     docId: doc._id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           fhirId: fhirResource.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 stockoutFlagsCount: fhirResource.extension?.length ?? 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ilmis: ilmisResponse,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             dhis2: dhis2Response
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       console.error('stock-report route error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return res.status(500).json({ error: err.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             module.exports = router;
