-- CHP-SCIS PostgreSQL schema
-- Runs automatically on first container start via docker-entrypoint-initdb.d
-- Database: cht (created by POSTGRES_DB env var)

-- ── stock_reports ──────────────────────────────────────────────────────────────
-- One row per CHP × commodity per report submission.
-- The FHIR mediator upserts here after receiving a CHT stock_report form.

CREATE TABLE IF NOT EXISTS stock_reports (
    doc_id             TEXT        NOT NULL,         -- CHT document _id
    chp_id             TEXT        NOT NULL,
    chp_name           TEXT,
    chu_id             TEXT        NOT NULL,          -- Community Health Unit
    commodity_code     TEXT        NOT NULL,          -- KEMSA commodity code
    commodity_name     TEXT,
    quantity_on_hand   INTEGER     NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0),
    quantity_dispensed INTEGER     NOT NULL DEFAULT 0 CHECK (quantity_dispensed >= 0),
    quantity_received  INTEGER     NOT NULL DEFAULT 0 CHECK (quantity_received >= 0),
    expiry_date        DATE,
    reported_date      TIMESTAMPTZ NOT NULL,
    has_stockout       BOOLEAN     NOT NULL DEFAULT false,
    fhir_resource      JSONB       NOT NULL,

    PRIMARY KEY (doc_id, commodity_code)
);

CREATE INDEX IF NOT EXISTS idx_sr_chu_id        ON stock_reports (chu_id);
CREATE INDEX IF NOT EXISTS idx_sr_chp_id        ON stock_reports (chp_id);
CREATE INDEX IF NOT EXISTS idx_sr_commodity     ON stock_reports (commodity_code);
CREATE INDEX IF NOT EXISTS idx_sr_reported_date ON stock_reports (reported_date DESC);
CREATE INDEX IF NOT EXISTS idx_sr_stockout      ON stock_reports (has_stockout) WHERE has_stockout = true;
CREATE INDEX IF NOT EXISTS idx_sr_fhir_gin      ON stock_reports USING GIN (fhir_resource);

-- ── supply_requests ────────────────────────────────────────────────────────────
-- One row per FHIR SupplyRequest generated by the stockout detector.
-- type = 'formal' : CHP requests resupply from attached facility (→ AfyaKE)

CREATE TABLE IF NOT EXISTS supply_requests (
    request_id         TEXT        PRIMARY KEY,   -- FHIR SupplyRequest.id (UUID)
    type               TEXT        NOT NULL CHECK (type IN ('formal')),
    requester_chp_id   TEXT        NOT NULL,
    facility_id        TEXT,                      -- attached facility (AfyaKE)
    chu_id             TEXT        NOT NULL,
    commodity_code     TEXT        NOT NULL,
    quantity_requested INTEGER     NOT NULL DEFAULT 1,
    status             TEXT        NOT NULL DEFAULT 'active'
                           CHECK (status IN ('active', 'completed', 'cancelled')),
    fhir_resource      JSONB       NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_req_requester    ON supply_requests (requester_chp_id);
CREATE INDEX IF NOT EXISTS idx_req_chu          ON supply_requests (chu_id);
CREATE INDEX IF NOT EXISTS idx_req_type         ON supply_requests (type);
CREATE INDEX IF NOT EXISTS idx_req_commodity    ON supply_requests (commodity_code);
CREATE INDEX IF NOT EXISTS idx_req_created      ON supply_requests (created_at DESC);

-- ── chp_stock_latest ──────────────────────────────────────────────────────────
-- View: most-recent stock quantity per CHP × commodity.
-- Used by /reports/stock and /reports/alerts for dashboard queries.

CREATE OR REPLACE VIEW chp_stock_latest AS
SELECT DISTINCT ON (chp_id, commodity_code)
    doc_id,
    chp_id,
    chp_name,
    chu_id,
    commodity_code,
    commodity_name,
    quantity_on_hand,
    quantity_dispensed,
    quantity_received,
    expiry_date,
    reported_date,
    has_stockout
FROM stock_reports
ORDER BY chp_id, commodity_code, reported_date DESC;
